stages:
  - validate
  - build
  - deploy

variables:
  NODE_ENV: production
  CONTENTFUL_SPACE_ID: $CONTENTFUL_SPACE_ID
  CONTENTFUL_ACCESS_TOKEN: $CONTENTFUL_ACCESS_TOKEN
  CONTENTFUL_PREVIEW_ACCESS_TOKEN: $CONTENTFUL_PREVIEW_ACCESS_TOKEN
  NETLIFY_AUTH_TOKEN: $NETLIFY_AUTH_TOKEN
  NETLIFY_SITE_ID: $NETLIFY_SITE_ID

validate:
  stage: validate
  image: node:20
  variables:
    NODE_ENV: 'development'
    NPM_CONFIG_PRODUCTION: 'false'
  script:
    - npm ci
    - npm run lint
    - npm run test:coverage
  artifacts:
    paths:
      - coverage
    expire_in: 1 week

build:
  stage: build
  image: node:20
  script:
    - npm ci
    - npm run build

deploy:
  stage: deploy
  image: node:20
  only:
    - main
  script:
    - npm install -g netlify-cli
    - netlify deploy --site $NETLIFY_SITE_ID --auth $NETLIFY_AUTH_TOKEN --prod
  after_script:
    - |
      if [ "$CI_JOB_STATUS" = "success" ]; then
        curl -H "Content-Type: application/json" \
             -d '{"text":"✅ Deploy concluído com sucesso no Netlify! 🎉"}' \
             "$TEAMS_WEBHOOK_URL"
      else
        curl -H "Content-Type: application/json" \
             -d '{"text":"❌ O deploy falhou no GitLab! Verifica o pipeline 😞"}' \
             "$TEAMS_WEBHOOK_URL"
      fi
