stages:
  - validate
  - build
  - deploy

variables:
  NODE_ENV: production
  CONTENTFUL_SPACE_ID: $CONTENTFUL_SPACE_ID
  CONTENTFUL_ACCESS_TOKEN: $CONTENTFUL_ACCESS_TOKEN
  CONTENTFUL_PREVIEW_ACCESS_TOKEN: $CONTENTFUL_PREVIEW_ACCESS_TOKEN
  NETLIFY_AUTH_TOKEN: $NETLIFY_AUTH_TOKEN
  NETLIFY_SITE_ID: $NETLIFY_SITE_ID

validate:
  stage: validate
  image: node:20
  variables:
    NODE_ENV: 'development'
    NPM_CONFIG_PRODUCTION: 'false'
  script:
    # Fail early with clear message when required Contentful variables are missing
    - |
      if [ -z "$CONTENTFUL_SPACE_ID" ]; then
        echo "ERROR: CONTENTFUL_SPACE_ID is not set in CI variables"; exit 1
      fi
    - |
      if [ -z "$CONTENTFUL_ACCESS_TOKEN" ]; then
        echo "ERROR: CONTENTFUL_ACCESS_TOKEN is not set in CI variables"; exit 1
      fi
    - |
      if [ -z "$CONTENTFUL_PREVIEW_ACCESS_TOKEN" ]; then
        echo "WARNING: CONTENTFUL_PREVIEW_ACCESS_TOKEN is not set (only needed for draft preview)"
      fi
    - npm ci
    - npm run lint
    - npm run test:coverage
  artifacts:
    paths:
      - coverage
    expire_in: 1 week

build:
  stage: build
  image: node:20
  script:
    - npm ci
    - npm run build

deploy:
  stage: deploy
  image: node:20
  only:
    - main
  script:
    - npm ci
    - npm run build
    - npm install -g netlify-cli
    # Upload the locally built `out` directory so Netlify does not run a remote build
    - netlify deploy --dir=out --site $NETLIFY_SITE_ID --auth $NETLIFY_AUTH_TOKEN --prod
  after_script:
    - |
      if [ -n "$TEAMS_WEBHOOK_URL" ]; then
        echo "TEAMS_WEBHOOK_URL appears set (length: ${#TEAMS_WEBHOOK_URL})"
        if [ "$CI_JOB_STATUS" = "success" ]; then
          payload='{"text":"✅ Deploy concluído com sucesso no Netlify (GitLab)! 🎉"}'
        else
          payload='{"text":"❌ O deploy falhou no GitLab! Verifica o pipeline 😞"}'
        fi
        echo "Sending notification to Teams (masked)..."
        # Capture curl exit and HTTP status without printing the webhook URL
        http_code=$(curl -s -S -o /tmp/teams_resp -w "%{http_code}" -H "Content-Type: application/json" -d "$payload" "$TEAMS_WEBHOOK_URL" || echo "CURL_FAILED")
        echo "curl returned: $http_code"
        if [ -f /tmp/teams_resp ]; then
          echo "Response body (first 200 chars):"
          head -c 200 /tmp/teams_resp | sed -n '1,200p'
        fi
      else
        echo "TEAMS_WEBHOOK_URL not set; skipping notification"
      fi
